#--------------------------------------------------------------------------------- #
#-- 1. 此配置文件将作为自定义配置文件，开发或者生产环境等都修改本配置文件来使配置生效；----- #
#-- 2. 修改配置项时强烈建议从 application.yml 中复制出配置项到本配置文件来单独修改；------ #
#-- 3. application-local.yml 配置文件中的配置优先级比 application.yml 配置文件要高；--- #
#-- 4. 运维人员需要注意的是，配置项的冒号(':')后面需要有一个空格，否则配置不会生效。------- #
#--------------------------------------------------------------------------------- #

# 服务使用的端口，默认 9999，可不用修改.
server:
  port: 9999

# Spring 相关配置.
spring:
  security:
    user:
      password: 123456
  jpa:
    show-sql: false # 是否打印 SQL 日志.

# 日志相关的简单配置.
logging:
  level:
    root: warn

# 本系统的相关配置.
system:
  load-json-data: false # 是否从 JSON 配置文件中加载保存网址导航分类和网址信息.
