<!-- 页脚内容. -->
<footer class="main-footer sticky footer-type-1">
    <div class="footer-inner">
        <div class="footer-text">
            Copyright &copy; 2021
            <a href="http://taoguoliang.cn" target="_blank">CXY备忘录</a>
        </div>
        <div class="go-up">
            <a href="#" rel="go-top">
                <i class="fa-angle-up"></i>
            </a>
        </div>
    </div>
</footer>