<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="author" content="blinkfox"/>
    <title>404 | CXY网址导航</title>
    <meta name="keywords" content="CXY网址导航">
    <meta name="description" content="CXY网址导航">

    <link rel="stylesheet" href="assets/css/fonts/linecons/css/linecons.css">
    <link rel="stylesheet" href="assets/css/fonts/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/bootstrap.css">
    <link rel="stylesheet" href="assets/css/xenon-core.css">
    <link rel="stylesheet" href="assets/css/xenon-components.css">
    <link rel="stylesheet" href="assets/css/xenon-skins.css">
    <link rel="stylesheet" href="assets/css/nav.css">
    <style type="text/css">
        .page-404 {
            margin-top: 100px;
        }
    </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="assets/js/html5shiv.min.js"></script>
    <script src="assets/js/respond.min.js"></script>
    <![endif]-->
</head>

<body class="page-body page-error-env page-404">
<div class="page-error centered">
    <div class="error-symbol">
        <i class="fa-warning"></i>
    </div>
    <h2>
        Error 404
        <small>你访问的页面不存在!</small>
    </h2>
    <p>我们没有定位到你需要访问的页面!</p>
    <p>我们建议你通过访问<a href="index"><i class="fa fa-home"></i> 首页</a>找到你需要的内容。</p>
</div>

</body>
</html>