<!DOCTYPE html>
<html lang="zh">
<head>
    <title>仪表盘 | CXY网址导航</title>
    <#include "commons/head.ftlh"/>
</head>

<body class="page-body">
    <!-- skin-white -->
    <div class="page-container">
        <#include "commons/sidebar.ftlh"/>
        <div class="main-content">
            <#include "commons/navbar.ftlh"/>
            <h3>待开发...</h3>

            <#include "commons/footer.ftlh"/>
        </div>
    </div>

    <#include "commons/script.ftlh"/>
</body>

</html>
